### PR TITLE
deactivate View Growth Curves

### PR DESCRIPTION
**Pull request by landml**
@briehl and @scanon 
Ticket to deactivate the app - https://kbase-jira.atlassian.net/browse/PTV-1497

### CODE REVIEW

**Comment by landml** [comment]
@psdehal - Is there anything I can do to get this merged so I can get the app deactivated.

**Comment by sychan** [comment]
Hi Miriam, this is failing because the .travis.yml file is just a stub, so Travis tries to run Ruby/Rails checks on it and that fails. Pull this file, add it to your PR and hopefully it should properly validate the YAML files and the spec file:
https://github.com/kbaseapps/kb_SetUtilities/blob/master/.travis.yml

**Comment by landml** [comment]
HI @sychan - I took your suggestion for updating .travis.yml on the NarrativeViewers module and it seems that it was still unsuccessful.

**Comment by sychan** [comment]
@landml Yeah, that travis file looks like it was a little old and broken. Try replacing the "install" section with the one from this repo
https://github.com/kbase/handle_service2/blob/develop/.travis.yml#L14

**Comment by sychan** [comment]
@landml I sent you a PR with the updated install section, try merging the PR and see if the travis build completes.

**Pull request merged**
