### PR TITLE
hopefully properly added the generic set view method

### PR DESCRIPTION
**Pull request by thomasoniii**
Pull request to add the hooks for the generic set viewer. Hopefully wired up properly, but please review for correctness.

Relevant mappings are already in narrative_method_specs_ci#develop in the types directory.

### CODE REVIEW

**Review by eapearson — COMMENTED** [review]
i'd suggest a semantically meaningful parameter name for param0 (just because they are a pain to change later.)
also, maybe nothing you can do about it, but a shame that in the output target properties, one is under_score and the other is camelCase, it adds dissonance.

**Comment by eapearson** [comment]
Other than that, it is hard to eyeball these specs; i'd suggest otherwise to merge, try it, iterate. The local build and the service registration process will do some correctness checks. But I am indeed rusty with this stuff. 

Generally I find that it is awkward to actually iterate quickly over a service, even just specs, esp. using PRS and with a shared development environment like CI in which registering a new dev tag make break the app for everyone. Still, in this case it would only break what you are working on, so low risk. There are alternatives, like using a branch on the main repo or creating your own rapid-development repo and registering that under a different name. But they introduce their own problems.

**Comment by eapearson** [comment]
I think you should add yourself as an owner in kbase.yml so that you can re-register the app in ci for testing. Then you can do the whole PR, merge, re-register cycle. But I guess that is a call for one of the current owners.

**Comment by briehl** [comment]
It also might be the case that 'param0' is a special name used by parts of the narrative system for wiring things together.

**Comment by briehl** [comment]
I just looked again. It's fine - the viewer cell stuff just expects a single parameter, which gets mapped either to an object name or reference, depending on the mapping section of the spec.

**Pull request merged**
